### ISSUE TITLE
Build error: Missing expobook-app.json

### ISSUE THREAD

**Issue by daniel** [teamplanes/expobook#15]
I get this error after creating a new Expo project and adding expobook according to the instructions.

```
expobook-test[ master #]$ ./node_modules/.bin/expobook
We've built a brand new CLI for Expo!
Expo CLI is a drop in replacement for exp.
Install: npm install -g expo-cli
Use: expo --help
Read more: https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c
[16:02:36] Using project at /Users/daniel/projects/_test/expobook-test
[16:02:37] Error: Missing expobook-app.json. See https://docs.expo.io/
[16:02:37] Couldn't start project. Please fix the errors and restart the project.
[16:02:37] Set EXPO_DEBUG=true in your env to view the stack trace.
child_process.js:651
    throw err;
    ^

Error: Command failed: cd /Users/daniel/projects/_test/expobook-test && /Users/daniel/projects/_test/expobook-test/node_modules/.bin/exp start --lan --ios --config /Users/daniel/projects/_test/expobook-test/__expobook__/expobook-app.json
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at runExpo (/Users/daniel/projects/_test/expobook-test/node_modules/expobook/cli.js:57:16)
    at ncp (/Users/daniel/projects/_test/expobook-test/node_modules/expobook/cli.js:20:5)
    at cb (/Users/daniel/projects/_test/expobook-test/node_modules/ncp/lib/ncp.js:255:37)
    at WriteStream.<anonymous> (/Users/daniel/projects/_test/expobook-test/node_modules/ncp/lib/ncp.js:133:14)
    at Object.onceWrapper (events.js:273:13)
    at WriteStream.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
```

package.json looks like this:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^32.0.0",
    "expobook": "0.0.5",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true
}
```

**Comment by flieks** [comment]
i got the same problem

**Comment by t-kabaya** [comment]
I solved this problem by applying below commit to my local file.
https://github.com/teamplanes/expobook/commit/0570bc1fba1c6673ab0a3d489e11fa3d30c1517e
Try!
