### ISSUE TITLE
Can this be used without expo?

### ISSUE THREAD

**Issue by cliren** [teamplanes/expobook#2]
Can expobook be used on a core react native project without using expo (or crna)?

**Comment by kirkness** [comment]
Correct - it has its own expo dependency so should work fine.

However, that being said It hasn't been rigorously tested on pure RN projects so please do feedback on this thread if you have problems!

**Comment by cliren** [comment]
@kirkness I created a repo for reproducing the issue on a pure RN project: I am running into an issue as stated in the README file https://github.com/cliren/rnbook

**Comment by cliren** [comment]
node: v8.11.1

I tried with the latest node and getting the following error. react-native is already installed, cleaned node_modules and did `npm install` and verified.

```

17:02:57 [exp] Using project at /Users/testuser/rn/rnbook
17:02:59 [exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
17:02:59 [exp] Error: React native is not installed. Please run `npm install` in your project directory.
17:02:59 [exp] Couldn't start project. Please fix the errors and restart the project.
17:02:59 [exp] Set EXPO_DEBUG=true in your env to view the stack trace.
child_process.js:644
    throw err;
    ^

Error: Command failed: cd /Users/testuser/rn/rnbook && /Users/testuser/rn/rnbook/node_modules/.bin/exp start --lan --ios --config /Users/testuser/rn/rnbook/__expobook__/expobook-app.json
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runExpo (/Users/testuser/rn/rnbook/node_modules/expobook/cli.js:57:16)
    at ncp (/Users/testuser/rn/rnbook/node_modules/expobook/cli.js:20:5)
    at cb (/Users/testuser/rn/rnbook/node_modules/ncp/lib/ncp.js:255:37)
    at WriteStream.<anonymous> (/Users/testuser/rn/rnbook/node_modules/ncp/lib/ncp.js:133:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)

```
